### ISSUE TITLE
Support iframe target sessions

### ISSUE THREAD

**Issue by YesperP** [joffrey-bion/chrome-devtools-kotlin#158]
**Problem**
Cross-origin iframes are created as new targets due to process isolation, and are not attached to the parent target session (page). This makes it impossible to control and get events on these iframes.

**Possible Solution**
It should be possible to create sessions to iframe-targets, similarly to a page.

Currently, attaching to a non-page target is blocked here. As well as "manually" creating sessions is blocked by the internal modifier.
https://github.com/joffrey-bion/chrome-devtools-kotlin/blob/main/src/main/kotlin/org/hildan/chrome/devtools/targets/TargetExtensions.kt

**Possible avoiding the problem:**
Disabling cross-orgin isolation with arguments:
--disable-site-isolation-trials --disable-web-security --disable-features=site-per-process,IsolateOrigins
but I got mixed results, and security impact may exist. Also, the behaviour could change in the future.
(https://stackoverflow.com/questions/51320322/how-to-disable-site-isolation-in-google-chrome)

Auto-attach:
Auto-attach commands are not working in this case. Cross-origin iframes are isolated and seems to be unable to attach.

**Comment by joffrey-bion** [comment]
Hi, thanks for opening this issue. This is an interesting use-case. 

I didn't expose too much of the internal types and constructors to try to provide the most type-safe experience possible. At the moment I only wrote proper types for the browser and page sessions, even though the interfaces for all types of targets are generated. I'm sorry that this prevents you from using iframes for now, I'll try to fix that.

You were saying you were blocked because of [this code here](https://github.com/joffrey-bion/chrome-devtools-kotlin/blob/main/src/main/kotlin/org/hildan/chrome/devtools/targets/TargetExtensions.kt#L21).
Could you please let me know the value for the target type you are getting for the iframe? Is it simply `iframe`?

Also, if you already have an example of public website using cross-origin iframes, it would be great if you could let me know so I can investigate more easily.

I guess I have 2 solutions. I could come-up with a generic solution that would allow consumers of the library to attach with any type of target and create their own types (such as making `AbstractTargetSession` non-sealed). But maybe a better solution would be to actually write the correct types for those (equivalent to `ChromePageSession`). I guess in your case probably the iframe is just another `RenderFrameTarget` and could therefore use the same `ChromePageSession` type actually.

**Comment by joffrey-bion** [comment]
After a couple manual tests, it seems the target type is indeed `iframe`, and the page session type seems suitable for this target type.

So I added support for this by just whitelisting `iframe` in addition to `page` for this method. Other target types may not work, so I'll leave them forbidden for now.

**Comment by joffrey-bion** [comment]
Released in version 3.6.0-973088. If all is well, it should land in Maven Central within a few minutes.

**Comment by YesperP** [comment]
Cool, thanks! Sounds reasonable to only allow iframes. 

I've been disabling security to disable isolated cross-origin iframes, I'll try changing some code and test this out as soon as possible to check the behaviour. 

Btw, this is such an amazing project! Makes everything way more reliable than puppeteer, etc. I've been trying to setup some sponsorship through github, but payments are not working. I'll try out paypal :)

**Comment by joffrey-bion** [comment]
Happy to hear that :) Don't hesitate to reopen this issue if the problem isn't solved, or open another one if you hit another roadblock.

I'm surprised about the sponsorship problem 🤔 Do you think it's something I could do something about? Or is it on your/github side? I already had payments via GitHub sponsors before, but maybe they changed something
