### ISSUE TITLE
Move some dependencies to mavenCenteral from jcenter?

### ISSUE THREAD

**Issue by cpdyj** [joffrey-bion/chrome-devtools-kotlin#78]
jcenter will terminate soon... emmm

**Comment by joffrey-bion** [comment]
I have changed the publication so that this library is published to maven central, and dependencies are fetched from maven central in priority.

But thanks for the report, I will look at dependencies and see if some are still on JCenter. Maybe they can simply be upgraded to a newer version that's on central.

Note that JCenter will stay up as read-only for a while in any case, so the transitive deps will be there ;)

**Comment by joffrey-bion** [comment]
FYI: The krossbow version I was using was still on JCenter. New versions of Krossbow are already on Maven central.
I will upgrade it, please follow this issue: https://github.com/joffrey-bion/chrome-devtools-kotlin/issues/84

I'm closing this one in favor of the more specific version upgrade.

**Comment by joffrey-bion** [comment]
The necessary upgrades were done in version 1.4.0-881010
