### ISSUE TITLE
Why we need disposeBrowserContext when close PageSession?

### ISSUE THREAD

**Issue by cpdyj** [joffrey-bion/chrome-devtools-kotlin#86]
The following code make me feel confuse. I only call pageSession.close(), but the whole browser is closed...
Is it a bug? Thank you.
 https://github.com/joffrey-bion/chrome-devtools-kotlin/blob/4b553ad4d92b08d879fc146f8d43569a04c037a6/src/main/kotlin/org/hildan/chrome/devtools/targets/TargetSessions.kt#L101

**Comment by joffrey-bion** [comment]
Hi, thanks for your report.

I'm curious as to how you use the API to have this behaviour.
Creating new pages with `attachToNewPage` using `incognito=true` should create independent browser contexts for each page, so it should not affect your other pages.

Are you creating targets manually? Could you please share a little sequence of what you do so I can use it as a test for your problem?

**Comment by cpdyj** [comment]
Hi, thanks for your reply.

First I open a list page, then I open some item pages from the list.(For some reason I must use `evalute("element.click()")` to open it.) The item page has the same context with the list page. After use I close the item page(using `pageSession.close()`) and open others.(I couldn't open them all at the same time because memory and CPU limit.) At that time close the whole context is a strange behavior.

**Comment by joffrey-bion** [comment]
Thanks a lot for sharing your use case! It will help design proper tests.

How do you get access to new `ChromePageSession`s from your initial page? How do you actually open new tabs from it?
I think this is the gist of the problem, and I should probably design something for that.

**Comment by joffrey-bion** [comment]
> For some reason I must use `evaluate("element.click()")` to open it

Could you please elaborate on this? Is there anything else in the protocol that you're lacking to click the element?
Or do you mean you wish there was a convenience method to click on a DOM element?

**Comment by cpdyj** [comment]
> How do you get access to new ChromePageSessions from your initial page?

Just `attachToNewPageAwaitPageLoading` (sorry maybe the method name has some mistake. I don't at company now that means I can't access the code.)

> How do you actually open new tabs from it?

Some element has additional eventlistener, I need trigger it.(Use click event). It's a normal element(such as `<a>`, `<div>`, etc...)
And sometimes, I need call some function directly. All these things can't achieve easily through the debugger API. `evaluate()` might be the easiest way. 

> Creating new pages with attachToNewPage using incognito=true should create independent browser contexts for each page, so it should not affect your other pages when you dispose of it.

And sometimes, I need use the current context directly, shared with normal user.

I agree with your opinion, close the whole context is a common case. But for other cases, provide a more clearly api is useful.

**Comment by joffrey-bion** [comment]
> > How do you actually open new tabs from it?
> 
> Some element has additional eventlistener, I need trigger it.(Use click event).

I tried replicating this in tests with an initial page with a `<a target="_blank" href="...">` link (to play the role of your "item list" page), and a second page where the link leads (to play the role of the item details page).

When I simulate the click on the link, it opens a new tab with the second page, and that tab gets the focus.
However, at that point the `ChromePageSession` still manages the initial tab (the item list in your case).

When I close the page session, it closes everything (which is I think what you described).
When I close the session without disposing of the browser context, it only closes the *initial* tab, but not the new one.

So it does not look like what you want to achieve, because you wanted to return to the list tab (AFAIU), but here you actually never leave it. What you would need is a way to attach a new page session to the tab that you create when you click a link, and then close that one without disposing of the browser context.
So I'm going to implement the API to keep the browser context, but you'll need more for your use case I believe.

**Comment by joffrey-bion** [comment]
In order to help you with your current issue, I added the following things:

* Allow to keep browserContext when closing a PageSession (https://github.com/joffrey-bion/chrome-devtools-kotlin/issues/89)
* Add helper to access "child pages" (https://github.com/joffrey-bion/chrome-devtools-kotlin/issues/92)
* Add utility to click on DOM element by selector (https://github.com/joffrey-bion/chrome-devtools-kotlin/issues/91)

This was released as part of `1.5.0-882324`. Please don't hesitate to open other issues if you face some problem.

**Comment by cpdyj** [comment]
Thank you for your work.
